### ISSUE TITLE
開かれたデプロイ権限が欲しい

### ISSUE THREAD

**Issue by nikezono** [masuilab/slack-hubot#33]
とか言ってもどうせ僕が卒業したら同じことを言う後輩が出てくると思うので

https://github.com/github/hubot-scripts/blob/master/src/scripts/update.coffee

こちらを導入してはいかがでしょう。

`hubot-scripts.json`に `update.coffee`を追記するだけでいけそうです。

**Comment by shokai** [comment]
herokuなので、コラボレータになってもらわないと無理です
ログも見れないし

**Comment by nikezono** [comment]
> herokuなので、コラボレータになってもらわないと無理です

https://github.com/github/hubot-scripts/blob/master/src/scripts/update.coffee

こちらを追加してもらって、`hubot update yourself`などのコマンドでhubot自身にアップデートさせる、という考えだったのですが、

確かにそもそもコラボレータになれなければupdateするものもpushできないですね。

**Comment by nikezono** [comment]
https://github.com/github/hubot-scripts/blob/master/src/scripts/update.coffee#L33

これの`remote`を任意に指定できたらどうなるんだろう

**Comment by shokai** [comment]
hubot、ひとり1hubot飼う方がいい気がしてて、色んな人のスクリプトを1つのhubotに持たせる意味あまりない気がしてる

**Comment by nikezono** [comment]
> hubot、ひとり1hubot飼う方がいい気がしてて、色んな人のスクリプトを1つのhubotに持たせる意味あまりない気がしてる

:+1:
